/**
 * AI RESCUEFLOW SHADOW — Emergency Response Orchestrator
 * Backend foundation for emergency response orchestration.
 * Activates ONLY after the RescueFlow Severity Engine confirms a collision.
 * 
 * STRICT REQUIREMENT:
 * The entire implementation MUST operate in SIMULATION MODE.
 * Never contact any real emergency services.
 * 
 * MANDATORY DISCLAIMER:
 * SIMULATION — NO REAL EMERGENCY SERVICES CONTACTED
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { resolveLocation } from './locationService.js';
import { findNearestServices } from './nearestServiceFinder.js';
import { createDispatchPlan, createTimeline, getSeverityPolicy } from './dispatchPlanner.js';
import { deduplicationService } from './deduplicationService.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SIMULATION_DISCLAIMER = 'SIMULATION — NO REAL EMERGENCY SERVICES CONTACTED';
const familyContactsPath = path.join(__dirname, '../data/demoFamilyContacts.json');

function loadFamilyContacts() {
  try {
    const raw = fs.readFileSync(familyContactsPath, 'utf-8');
    return JSON.parse(raw);
  } catch (err) {
    console.error('Failed to load demo family contacts:', err);
    return [];
  }
}

/**
 * Validates whether a collision has been confirmed by the RescueFlow Severity Engine.
 * Accepts an incident report, confirmation payload, or collision flag.
 */
export function isCollisionConfirmed(input) {
  if (!input) return false;

  // 1. Explicit collision boolean
  if (input.isCollisionConfirmed === true || input.collisionConfirmed === true) {
    return true;
  }

  // 2. Incident report generated by rescueEngine.js
  if (input.status === 'ACTIVE_RESPONSE' && input.severity && (input.severity.level || typeof input.severity === 'string')) {
    return true;
  }

  // 3. Impact analysis confirmation
  if (input.impactAnalysis && (input.impactAnalysis.relativeImpactSpeedKmH > 0 || input.impactAnalysis.gForceVehicleB > 0)) {
    return true;
  }

  return false;
}

/**
 * Orchestrates emergency response for a confirmed collision.
 * Activates ONLY after collision confirmation.
 * 
 * @param {Object} incidentPayload - Incident or collision data from RescueFlow Severity Engine
 * @returns {Object} Orchestrator response containing dispatch plan, timeline, and simulation disclaimer.
 */
export function orchestrateEmergencyResponse(incidentPayload = {}) {
  // Gate check: Activate ONLY after RescueFlow Severity Engine confirms collision
  const confirmed = isCollisionConfirmed(incidentPayload);

  if (!confirmed) {
    return {
      activated: false,
      incidentId: incidentPayload?.incidentId || null,
      status: 'BLOCKED_COLLISION_NOT_CONFIRMED',
      reason: 'Emergency Response Orchestrator activates ONLY after the RescueFlow Severity Engine confirms a collision.',
      simulationDisclaimer: SIMULATION_DISCLAIMER
    };
  }

  const incidentId = incidentPayload.incidentId || `INC-SIM-${Date.now().toString().slice(-6)}`;
  
  // Extract severity level (LOW, MODERATE, HIGH, CRITICAL, CATASTROPHIC)
  let severity = 'MODERATE';
  if (typeof incidentPayload.severity === 'string') {
    severity = incidentPayload.severity.toUpperCase();
  } else if (incidentPayload.severity?.level) {
    severity = incidentPayload.severity.level.toUpperCase();
  } else if (incidentPayload.severityLevel) {
    severity = String(incidentPayload.severityLevel).toUpperCase();
  }

  const policy = getSeverityPolicy(severity);
  const responsePriority = policy.displayPriority;

  // Extract or default location coordinates
  const telemetry = incidentPayload.telemetry || incidentPayload;
  const rawLat = incidentPayload.latitude ?? telemetry?.latitude ?? 37.7749;
  const rawLon = incidentPayload.longitude ?? telemetry?.longitude ?? -122.4194;
  const heading = incidentPayload.heading ?? telemetry?.heading ?? telemetry?.vehicleA?.heading ?? 45;
  const timestamp = incidentPayload.timestamp || new Date().toISOString();

  // 1. Resolve Location via offline location service
  const location = resolveLocation({
    latitude: rawLat,
    longitude: rawLon,
    timestamp,
    vehicleHeading: heading
  });

  // 2. Find Nearest Emergency Facilities (Hospital & Police Station)
  const nearestServices = findNearestServices(location.coordinates);
  const selectedHospital = nearestServices['nearest hospital'];
  const selectedPoliceStation = nearestServices['nearest police station'];

  // 3. Load & Deduplicate Family Recipients
  const rawFamily = incidentPayload.familyContacts || loadFamilyContacts();
  
  // Apply deduplication: each recipient notified only once per incident
  const familyRecipients = [];
  for (const contact of rawFamily) {
    const contactKey = contact.id || contact.phone || contact.email;
    if (deduplicationService.canNotify(incidentId, contactKey)) {
      const recordResult = deduplicationService.recordAttempt(incidentId, contactKey, 'DISPATCHED');
      if (recordResult.allowed) {
        familyRecipients.push({
          ...contact,
          dispatchRecord: recordResult.record
        });
      }
    }
  }

  // Deduplicate Hospital notification if policy dispatches hospital
  if (policy.hospitalDispatched && selectedHospital) {
    deduplicationService.recordAttempt(incidentId, selectedHospital.id, 'DISPATCHED');
  }

  // Deduplicate Police notification if policy dispatches police
  if (policy.policeDispatched && selectedPoliceStation) {
    deduplicationService.recordAttempt(incidentId, selectedPoliceStation.id, 'DISPATCHED');
  }

  // 4. Generate Dispatch Plan
  const dispatchPlanResult = createDispatchPlan({
    incidentId,
    severity,
    location,
    selectedHospital,
    selectedPoliceStation,
    familyRecipients
  });

  // 5. Generate Response Timeline
  const timeline = createTimeline(severity, location);

  // 6. Return standard schema
  return {
    activated: true,
    incidentId,
    severity,
    responsePriority,
    selectedHospital,
    selectedPoliceStation,
    familyRecipients,
    dispatchPlan: dispatchPlanResult.dispatches,
    timeline,
    simulationDisclaimer: SIMULATION_DISCLAIMER,
    location,
    metadata: {
      activatedAt: new Date().toISOString(),
      policyApplied: policy.recipients,
      simulationMode: true
    }
  };
}

export const emergencyResponseOrchestrator = {
  orchestrateEmergencyResponse,
  isCollisionConfirmed,
  SIMULATION_DISCLAIMER
};

export default emergencyResponseOrchestrator;
